services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - db_data:/data
      - /app/node_modules
    environment:
      - DB_PATH=/data/transcendence.db

volumes:
  db_data: