services:
  frontend:
    build: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app             # <-- TRÈS IMPORTANT : Monte tout le code source frontend
      - /app/node_modules           # Exclut node_modules
    # ... autres configs comme les ports si tu as un serveur de dev frontend

  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app              # Monte le code source backend
      - /app/node_modules
      - ./frontend/public:/app/public # <-- TRÈS IMPORTANT : Le backend lit le public de l'hôte
    ports:
      - "3001:3001"
    environment:
      - DB_PATH=/app/transcendence.db
    env_file:
      - ./backend/.env

# Assure-toi que la section 'volumes:' pour 'frontend-public' est commentée ou supprimée :
# volumes:
#   frontend-public: