services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend-public:/app/public  # ← public compilé ici

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - frontend-public:/app/frontend/public  # ← lecture des fichiers ici
    ports:
      - "3001:3001"
    environment:
      - DB_PATH=/app/transcendence.db
    env_file:
      - ./backend/.env

volumes:
  frontend-public:
