services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules  # ← ajoute cette ligne !
    environment:
      - DB_PATH=/app/transcendence.db
    env_file:
    - ./backend/.env
