services:
  frontend:
    build: ./frontend
    working_dir: /app
    volumes:
      - /app/node_modules           # évite les conflits de dépendances locales
      - frontend-public:/app/public  # output de `npm run build` ici

  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app              # monte ton code backend
      - /app/node_modules
      - frontend-public:/app/public  # récupère les fichiers compilés du frontend
    ports:
      - "3001:3001"
    environment:
      - DB_PATH=/app/transcendence.db
    env_file:
      - ./backend/.env

volumes:
  frontend-public:
