services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - network
    restart: unless-stopped
    volumes:
      -  ./frontend:/var/www/html:ro

networks:
  network:
    driver: bridge
