services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    command: sh -c "npm run build && serve -s public -l 3000"
